server:
  port: 9001

# microservice ?? ID??
spring:
  application:
    name: user-service

# eureka client
eureka:
  client:
    register-with-eureka: true #eureka ????? ?????? ??? ????? ??? ???? ???? ??, true? ????, ?? ? ??? ???? ??
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka  #micro service ??

