server:
  port: 8761

# microservice ?? ID??
spring:
  application:
    name: discoveryservice

# eureka client
# ? ??? ????? client ??? ??? ??? ?? ?????? ???? ???? ??? ?????? ???? ??? ??.
# ??? ??? ???? ???? ???? ???? ??? false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false